const EErrors = {
    ROUTING_ERRORS: 1,
    INVALID_TYPES_ERRORS: 2,
    DATA_BASE_ERRORS: 3,
    USER_NOT_FOUND: 4,
    EMPTY_CART: 5,
    PRODUCT_UNAVAILABLE: 6,
    PAYMENT_ERROR: 7,
    TICKET_NOT_GENERATED: 8,
    INCOMPLETE_REGISTRATION: 9,
    PRODUCT_NOT_FOUND: 10,
    PRODUCT_IN_STOCK: 11,
    UPDATING_ERROR: 12,
    DELETE_ERROR: 13,
    CART_NOT_FOUND: 14

}
export default EErrors